CREATE TABLE ACCOUNTS (
    ID UUID PRIMARY KEY,
    USERNAME VARCHAR(20),
    PASSWORD_HASH VARCHAR(60),
    IS_GUEST_ACCOUNT BOOLEAN,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP
);

CREATE UNIQUE INDEX ON ACCOUNTS(USERNAME);