CREATE TABLE ACCOUNTS (
    ID UUID PRIMARY KEY,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD_HASH VARCHAR(60),
    IS_GUEST_ACCOUNT BOOLEAN NOT NULL DEFAULT FALSE,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX ON ACCOUNTS(LOWER(USERNAME));